### ISSUE TITLE
Loading /Users/danielkrah/Downloads/Heatbed_MK52_magnetic-master/24V_05d/Heatbed-MK52.sch | error: Start tag expected.

### ISSUE THREAD

**Issue by Moorviper** [prusa3d/Heatbed_MK52_magnetic#1]
Hi 
I can't open the file

**Comment by ok1hra** [comment]
We use newest version of Kicad, need compile from Git. More here
http://docs.kicad-pcb.org/doxygen/md_Documentation_development_compiling.html

**Comment by Moorviper** [comment]
ah ok / opened with eagle now it is fine
